### ISSUE TITLE
Ordered list syntax doesn't seem to work

### ISSUE THREAD

**Issue by Russpd** [jack7890/mkdown#24]
I must be doing something stupid, but having trouble getting ordered lists to work using the syntax from [this article](http://daringfireball.net/projects/markdown/syntax#list)

**Comment by jack7890** [comment]
Seems that this is currently a problem in Chrome but not FF

**Comment by jack7890** [comment]
Need to change this to `decimal`:

![screen shot 2015-11-03 at 5 55 22 pm](https://cloud.githubusercontent.com/assets/23845/10924340/163774d0-8254-11e5-8a27-a00677f41d85.png)

**Comment by jack7890** [comment]
Fixed by @erwaller
